'use strict';
const $ = id => document.getElementById(id);
const bots = [
  {name:'ETHEREUM BOT',coin:'eth',yield:'65.23',deposit:'531',time:'2Д',mode:'LONG 1X',type:'ФЬЮЧЕРС',path:'M0 48 L22 48 L26 40 L43 40 L47 27 L71 27 L75 15 L95 15 L100 12 L143 12 L149 5 L158 3 L173 3',icon:'<path fill="#fff" d="M17 1 3 21 17 28 31 21Z"/><path fill="#c1cbff" d="m17 1 0 27 14-7Z"/><path fill="#fff" d="m3 24 14 8 14-8-14 17Z"/><path fill="#c1cbff" d="m17 32 14-8-14 17Z"/>'},
  {name:'SOLANA BOT',coin:'sol',yield:'52.01',deposit:'301',time:'11Ч',mode:'LONG 1X',type:'ФЬЮЧЕРС',path:'M0 48 L8 48 L12 43 L36 43 L40 34 L58 34 L64 27 L75 27 L79 21 L128 21 L132 16 L159 16 L164 3 L173 3',icon:'<defs><linearGradient id="sol-color" x1="0" y1="1" x2="1" y2="0"><stop stop-color="#a35eff"/><stop offset="1" stop-color="#00eca5"/></linearGradient></defs><path fill="url(#sol-color)" d="m7 5-5 7h26l5-7Zm-5 12 5 7h26l-5-7Zm5 12-5 7h26l5-7Z"/>'},
  {name:'LOW GRAM BOT',coin:'gram',yield:'84.26',deposit:'354',time:'6Ч',mode:'☰ СЕТКА',type:'СПОТ',path:'M0 48 L5 45 L22 45 L26 42 L50 42 L54 36 L78 36 L83 18 L119 18 L123 9 L138 9 L143 3 L173 3',icon:'<path fill="#fff" d="m8 6-7 12 16 19 16-19-7-12Z"/><path fill="#299fec" d="m17 10 2.5 6 6 2.5-6 2.5-2.5 6-2.5-6-6-2.5 6-2.5Z"/>'}
];
$('bot-cards').innerHTML=bots.map((b,i)=>`<article class="bot-card"><div class="bot-heading"><span class="coin ${b.coin}"><svg viewBox="0 0 34 42" aria-hidden="true">${b.icon}</svg></span><div><h3>${b.name}</h3><div class="tags"><span class="tag">${b.mode}</span><span class="tag ${b.type==='СПОТ'?'spot':'future'}">▱ ${b.type}</span></div></div></div><div class="yield"><p class="eyebrow">ГОДОВАЯ ДОХОДНОСТЬ <span aria-label="Демонстрационный показатель">ⓘ</span></p><div class="performance"><span class="percent">+${b.yield}%</span><span class="trend" aria-hidden="true">↗</span><svg class="chart" viewBox="0 0 173 52" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="chart-${i}" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#00d47e" stop-opacity=".22"/><stop offset="1" stop-color="#00d47e" stop-opacity="0"/></linearGradient></defs><path d="${b.path} L173 52 L0 52Z" fill="url(#chart-${i})"/><path d="${b.path}" stroke="#39d57d" stroke-width="1" fill="none"/></svg></div></div><dl class="bot-stats"><div class="stat"><dt>РИСК ЛИКВИДАЦИИ</dt><dd>ОТСУТСТВУЕТ</dd></div><div class="stat"><dt>МИНИМАЛЬНЫЙ ДЕПОЗИТ</dt><dd>$${b.deposit}</dd></div><div class="stat"><dt>СРЕДНЕЕ ВРЕМЯ СДЕЛКИ</dt><dd>${b.time}</dd></div></dl><button class="locked" disabled>Сначала пополните депозит,<br>чтобы запустить</button></article>`).join('');
const networks={
  ton:{title:'GRAM',former:'бывший «TON»',code:'',icon:'gram',label:'USDT · GRAM — бывший «TON»',name:'TON',demo:false,address:'UQD5WrYyQZ1XXYwish1vhCQJ6OE6I4wKhBp7PTCGNsq-yo0P'},
  bnb:{title:'BNB Smart Chain',code:'BEP20',icon:'bnb',label:'USDT · BNB Smart Chain «BEP20»',name:'BNB Smart Chain (BEP20)',demo:false,address:'0xFd277343aE483FBc37451c2Cde40538Bd8459d99'},
  tron:{title:'TRON',code:'TRC20',icon:'tron',label:'USDT · TRON «TRC20»',name:'TRON (TRC20)',demo:false,address:'TAP4pPsukzahQkwcXLHK38GhgUNb8aeSsx'},
  polygon:{title:'Polygon',code:'PoS',icon:'polygon',label:'USDT · Polygon «PoS»',name:'Polygon PoS',demo:false,address:'0xFd277343aE483FBc37451c2Cde40538Bd8459d99'},
  solana:{title:'Solana',code:'',icon:'solana',label:'USDT · Solana',name:'Solana',demo:false,address:'FSTJFYZ78q1xCjAyBCrHYZyVnaKYagDGTzLTuiV6LV59'},
  ethereum:{title:'Ethereum',code:'ERC20',icon:'ethereum',label:'USDT · Ethereum «ERC20»',name:'Ethereum (ERC20)',demo:false,address:'0xFd277343aE483FBc37451c2Cde40538Bd8459d99'}
};
$('network-options').innerHTML=Object.entries(networks).map(([id,n])=>`<button class="network" data-network="${id}" aria-pressed="false"><span class="network-icon ${id}" aria-hidden="true"><img src="assets/${n.icon}.svg" alt="" width="44" height="44"></span><span class="network-text"><strong>${n.title}${n.former?` <span class="former-name">${n.former}</span>`:''}</strong><small>USDT${n.code?` <span class="network-code">«${n.code}»</span>`:''}</small></span><span class="radio" aria-hidden="true"></span></button>`).join('');
let selected=null,toastTimer,copyTimer,authTimer;
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600);}
function resetCopy(){clearTimeout(copyTimer);$('copy').querySelector('span').textContent='Копировать';}
function route(){const page=location.hash.slice(1);const inApp=['bots','deposit'].includes(page);$('landing').hidden=inApp;$('workspace').hidden=!inApp;document.querySelector('.language').classList.toggle('app-language',inApp);$('bots-page').hidden=page!=='bots';$('deposit-page').hidden=page!=='deposit';if(page==='bots')$('bots-nav').setAttribute('aria-current','page');else $('bots-nav').removeAttribute('aria-current');if(page!=='deposit'){selected=null;$('address-block').hidden=true;document.querySelectorAll('.network').forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-pressed','false');});resetCopy();}window.scrollTo(0,0);document.title=page==='bots'?'Шаблоны ботов — Nexet':page==='deposit'?'Пополнение баланса — Nexet':'Nexet — тестовая версия';}
$('authorize').addEventListener('click',()=>{$('authorize').disabled=true;$('authorize').textContent='Авторизовано ✓';toast('Авторизовано ✓');authTimer=setTimeout(()=>{location.hash='bots';$('authorize').disabled=false;$('authorize').textContent='Авторизоваться';},750);});
$('logout').addEventListener('click',()=>{clearTimeout(authTimer);location.hash='';$('authorize').disabled=false;$('authorize').textContent='Авторизоваться';});
document.querySelectorAll('.network').forEach(button=>button.addEventListener('click',()=>{selected=button.dataset.network;resetCopy();document.querySelectorAll('.network').forEach(b=>{const active=b===button;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});const n=networks[selected];$('address').textContent=n.address;$('network-badge').textContent=n.label;$('network-warning').textContent=`Для реального пополнения используйте USDT только в сети ${n.name}. Перевод через другую сеть может привести к потере средств.${n.demo===false?'':' Адрес демонстрационный — не переводите на него средства.'}`;$('address-block').hidden=false;}));
async function copyAddress(){if(!selected)return;const value=networks[selected].address;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(value);}else{const area=document.createElement('textarea');area.value=value;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();const ok=document.execCommand('copy');area.remove();if(!ok)throw new Error('clipboard');}$('copy').querySelector('span').textContent='Скопировано ✓';toast('Адрес скопирован');copyTimer=setTimeout(resetCopy,2200);}catch{toast('Не удалось скопировать. Выделите адрес и скопируйте вручную.');}}
$('copy').addEventListener('click',copyAddress);
window.addEventListener('hashchange',route);route();
